# Generated by Django 5.0.1 on 2024-03-14 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('formato_pago', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('password1', models.CharField(default='', max_length=100)),
                ('password2', models.CharField(default='password', max_length=128)),
                ('direccion', models.CharField(default='', max_length=100)),
                ('formato_pago', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('numero_pedidos', models.IntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Entragado', 'Entregado')], max_length=100)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.lista_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=4, max_digits=100)),
                ('idpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('zise1', models.CharField(max_length=10)),
                ('colores', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='static/')),
                ('precio', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='idproducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.producto'),
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empledo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=200)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Sueldo',
            fields=[
                ('id_sueldo', models.AutoField(primary_key=True, serialize=False)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('numero_venta', models.IntegerField()),
                ('fecha', models.DateField()),
                ('idfactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.factura')),
                ('idpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.pedido')),
            ],
        ),
    ]
