# Generated by Django 5.0.1 on 2024-04-04 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='carrusel/')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.producto')),
            ],
        ),
    ]
