# Generated by Django 5.0.4 on 2025-01-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_carrusel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='modelousuario',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='modelousuario',
            name='password2',
        ),
    ]
