# Generated by Django 5.0.4 on 2025-04-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_lista_megusta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='colores',
            field=models.TextField(default='', help_text='colores separados por coma: rojo,azul,verde'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='zise1',
            field=models.TextField(default='', help_text='Tallas separadas por coma: S,M,L'),
        ),
    ]
