# Generated by Django 5.0.4 on 2025-04-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_producto_colores_alter_producto_zise1'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='material',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
