# Generated by Django 5.0.4 on 2025-05-14 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_remove_pedido_idproducto_detallepedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefo', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=255)),
                ('forma_pago', models.CharField(choices=[('tarjeta de credito o devito', 'Tarjeta de credito o devito'), ('pago contra entrega', 'Pago contra entrega'), ('paypal', 'Paypal')], max_length=50)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.pedido')),
            ],
        ),
    ]
