# Generated by Django 5.0.4 on 2025-05-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_alter_pedido_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
    ]
