# Generated by Django 5.0.4 on 2025-05-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0020_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('recibido', 'recibido'), ('preparando', 'preparando'), ('empacado', 'empacado'), ('encamino', 'encamino'), ('entregado', 'entregado')], max_length=100),
        ),
    ]
